export const Filter = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
    SHOW_COMPLETED: 'SHOW_COMPLETED'
}
export const SHOW_FILTEDATA = 'SHOW_FILTEDATA'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const COMPLETED_ALL_TODO = 'COMPLETED_ALL_TODO'
export const CLEAR_COMPLETED_TODO = 'CLEAR_COMPLETED_TODO'

